### ISSUE TITLE
Consider using Pipenv for dependency management

### ISSUE THREAD

**Issue by bartlomieju** [vespene-io/vespene#15]
Pipenv is now considered a recommended way to handle dependencies in Python. 

I personally find it much more pleasant to work with Pipenv instead of using `virtualenv` manually.

Edit: typo

**Comment by danpalmer** [comment]
For what it's worth, I don't think Pipenv has passed the "interesting proposal" stage yet within the Python community. There are competing proposals such as [Poetry](https://poetry.eustace.io), and major projects generally aren't jumping on Pipenv yet as it still has much to prove in terms of integration with the rest of the ecosystem. We've experimented with it on my team and are sticking with `pip-tools` and `virtualenv` for now.

**Comment by apollo13** [comment]
I also disagree with the assumption that pipenv is in any way a recommended tool. It is imo way to unstable and slow. I do not think there is any gain in switching to pipenv at this point.

**Comment by mpdehaan** [comment]
First I've heard of pipenv actually, but I don't always follow the new proposals.

Yeah just to be clear for those reading, the production setup doesn't even use virtualenv, because we expect Vespene to be installed on it's own VMs, and that also makes everything complicated with respect to Python path, environment activition, and all sorts of cruft.

In development, you're welcome to use whatever you want to use.

Appreciate all the commentary from those that are more plugged in on this.  I find the virtualenv process to be pretty easy to use and everybody I know tends to work that way, so I think we're going to leave it like this for now.

If this changes in the future, seeing it's mostly developer setup instructions, this would mostly be a docs change.
