### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by mikebywater** [vespene-io/vespene#28]
Would it be useful to have a docker compose file that installs on an ubuntu container with maybe a separate postgresql container?

**Comment by mpdehaan** [comment]
Yes, I totally agree for this.  There's some good discussion about how to start this on http://talk.vespene.io at the moment.  

I'm going to close this ticket because I don't want keep RFEs here so much, but the forum discussion is still there.  Do you want to perhaps stop by the forum and make some suggestions?

https://talk.vespene.io/t/ability-to-contanerize-the-components-of-vespene/30/6

Thank you!
