### ISSUE TITLE
docs: Detail the setup process

### ISSUE THREAD

**Issue by chopraaa** [vespene-io/vespene#77]
I think the setup process needs to be a bit more detailed and reformatted for readability.

* Poor readability at the moment. The docs just seem like a wall of text. I can submit a PR for this if required. +1 for inline code as well. 

* A link to the FAQ and more directions for troubleshooting would be great too. Using an external Postgres database, creating firewall rules to whitelist gunicorn, and so on. (DigitalOcean and Vultr have firewalls enabled in images it seems)

* Point out what's stored in these:

        /opt/vespene
        /etc/vespene
        /var/log/vespene
        /var/spool/vespene
        /tmp/vespene/

    I mean sure, I know Vespene's using these but what for? Where are the builds stored? Where can I keep project files? Is a `.vespene` file created when I create a project? Where is it?

* `GUNICORN_OPTS="--bind 127.0.0.1:8000"` was changed to `GUNICORN_OPTS="--bind 0.0.0.0:8000"` and back to `GUNICORN_OPTS="--bind 127.0.0.1:8000"`. I was following the setup guide on docs.vespene.io so I didn't catch this and figured it was still using `0.0.0.0`. 

    This should go into the docs since we're asking people to run the scripts and not giving specific instructions on installing Vespene.

* Since hostnames are used for referring to build workers, one way would be to refer to the master host using it's hostname as well to avoid the `127.0.0.1` and `0.0.0.0` issue.

**Edit**: TIL there's also http://docs.vespene.io/development_setup.html ;_;

**Comment by mpdehaan** [comment]
Hi,

This is really a lot of different things.

If you would like to discuss them I would suggest commenting on the docs topic on talk.vespene.io and I can go into detail on each. The forum is for feedback and this queue is for bugs.

Regardless, some comments now:

The hostname is not public because without a SSL configuration it would be an insecure default. This can be provided through gunicorn or NGINX/Apache. That could possibly be added to the security guide.

I think most poeple know what those paths mean but I’m open to some clarification and thoughts from multiple readers are welcome. Vespene projects live in the database and .vespene files live in the source git repos.

Anyway if you can stop by the forum docs feedback thread that would be great!

I would not spend time on rewriting my docs - I’m very opinionated there and these took weeks to write - and there is a chance edits may lose some detail.
